version: '3.1'

volumes:
  pdata:

services:
  db2-postgres:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: db2-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pdata:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
