version: "3"

services:
    elasticsearch:
        container_name: elasticsearch
        image: elasticsearch:8.4.2
        environment:
          - "discovery.type=single-node"
        ports:
          - 9200:9200
          - 9300:9300
